const actionEnum = {
  FETCHING_DATA: 'FETCHING_DATA',
  FETCHING_DATA_SUCCESS: 'FETCHING_DATA_SUCCESS',
  FETCHING_DATA_PEOPLE_SUCCESS: 'FETCHING_DATA_PEOPLE_SUCCESS',
  FETCHING_DATA_FAILURE: 'FETCHING_DATA_FAILURE',
};


export default actionEnum;
